### ISSUE TITLE
Change visited styles on documentation navigation 

### ISSUE THREAD

**Issue by nZac** [TeamSkosh/fuselage#40]
![screen shot 2015-06-15 at 10 47 10 am](https://cloud.githubusercontent.com/assets/276212/8163998/f6944846-134b-11e5-8570-45e0cb426637.png)

What are your thoughts on keeping the visited style for the navigation the same as the regular style?

**Comment by randseay** [comment]
I think that's a good idea. It stems from the paragraph link styles. Are you proposing removing the visited styles altogether, or just in this navigation?

**Comment by nZac** [comment]
Just in the navigation. The three colors confuse me.

**Comment by randseay** [comment]
This will be fixed as soon as the project site upgrades Fuselage to 1.0.0
